<a href="https://colab.research.google.com/github/Ashwin0706-dev/AIML-boot/blob/main/AIMLboot3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
from sklearn.cluster import SpectralClustering
from sklearn.metrics import silhouette_score
from sklearn.metrics.pairwise import cosine_similarity
df=pd.read_csv('social_network.csv')
print("original Dataset:")
display(df)

students=df["Student"]
X=df.drop("Student",axis=1)
print("\nStudent Names:")
print(students.tolist())
print("\nFeature Matrix:")
display(X)

A=cosine_similarity(X)
print("\nCosine Similarity Matrix:")
print(np.round(A,3))

degree=A.sum(axis=1)
print("\nDegree of each Student:")
for student,d in zip(students,degree):
  print(student,":",round(d,3))

D=np.diag(degree)
print("\nDegree Matrix:")
print(np.round(D,3))

L=D-A
print("\nLaplacian Matrix:")
print(np.round(L,3))

n_clusters=2
model=SpectralClustering(
    n_clusters=n_clusters,
    affinity="precomputed",
    random_state=42
)
labels=model.fit_predict(A)

result=pd.DataFrame({
    "Student":students,
    "Cluster":labels
})
result["Cluster"]=result["Cluster"]+1
print("\nCluster Results:")
display(result)

silhouette_labels = result["Cluster"] - 1

score = silhouette_score(
    X,
    silhouette_labels
)

print("\nSilhouette Score:", round(score, 4))

original Dataset:

   Student  Sports  Movies  Music  Coding
0      Anu       1       1      1       0
1     Bala       1       1      1       1
2  Chandru       1       1      1       1
3    Divya       0       1      1       1
4     Elan       0       0      0       1
5    Farah       0       0      0       1

Student Names:
['Anu', 'Bala', 'Chandru', 'Divya', 'Elan', 'Farah']

Feature Matrix:

   Sports  Movies  Music  Coding
0       1       1      1       0
1       1       1      1       1
2       1       1      1       1
3       0       1      1       1
4       0       0      0       1
5       0       0      0       1

Cosine Similarity Matrix:
[[1.    0.866 0.866 0.667 0.    0.   ]
 [0.866 1.    1.    0.866 0.5   0.5  ]
 [0.866 1.    1.    0.866 0.5   0.5  ]
 [0.667 0.866 0.866 1.    0.577 0.577]
 [0.    0.5   0.5   0.577 1.    1.   ]
 [0.    0.5   0.5   0.577 1.    1.   ]]

Degree of each Student:
Anu : 3.399
Bala : 4.732
Chandru : 4.732
Divya : 4.553
Elan : 3.577
Farah : 3.577

Degree Matrix:
[[3.399 0.    0.    0.    0.    0.   ]
 [0.    4.732 0.    0.    0.    0.   ]
 [0.    0.    4.732 0.    0.    0.   ]
 [0.    0.    0.    4.553 0.    0.   ]
 [0.    0.    0.    0.    3.577 0.   ]
 [0.    0.    0.    0.    0.    3.577]]

Laplacian Matrix:
[[ 2.399 -0.866 -0.866 -0.667  0.     0.   ]
 [-0.866  3.732 -1.    -0.866 -0.5   -0.5  ]
 [-0.866 -1.     3.732 -0.866 -0.5   -0.5  ]
 [-0.667 -0.866 -0.866  3.553 -0.577 -0.577]
 [ 0.    -0.5   -0.5   -0.577  2.577 -1.   ]
 [ 0.    -0.5   -0.5   -0.577 -1.     2.577]]

Cluster Results:

   Student  Cluster
0      Anu        1
1     Bala        1
2  Chandru        1
3    Divya        1
4     Elan        2
5    Farah        2

Silhouette Score: 0.6427